// The file maintail all application constants and resuse across the application.
import { environment } from 'src/environments/environment.development';
export const applicationConstants = {

    AUTHENTICATION: environment.rbac,
    GET_DYNAMIC_MENUS: '/users/user_access_menus',
    ADD_URL: '/add',
    ADD_ALL_URL: '/add_all',
    UPDATE_URL: '/update',
    GET_ALL_URL: '/get_all',
    GET_ALL_ACTIVE: '/get_all_active',
    ORDER_ALREADY_EXIST: 'Order Already Exist',
    GET_URL: '/get',
    DELETE_URL: '/remove',
    HEADER_AUTHEN_KEY: 'authToken',
    HEADER_USER_KEY: 'userid',
    HEADER_CONTENT_TYPE: 'Content-Type',
    roleId: "roleId",
    STATUS_SUCCESS: 'SUCCESS',
    STATUS_ERROR: 'ERROR',
    STATUS_WARN: 'WARNING',
    SIGN_IN: '/signin',
    USERS: '/users',
    BOND_TYPES: '/bond_types',
    CLEAR_TOKEN: '/clear_token',
    TYPE_OF_TENURE: '/type_of_tenure',
    sign_up: "/sign_up",
    LOGIN: '/',
    SIGNED_IN: '/signed_in',
    CHECK_USER_LOGIN: '/check_user_login',
    SEND_MOBILE_OTP: '/send_mobile_otp',
    SEND_EMAIL_OTP: '/send_email_otp',
    userId: 'userId',
    PACS_ID: 'pacsId',
    BRANCH_ID: 'branchId',
    userName: 'userName',
    WE_COULDNOT_PROCESS_YOU_ARE_REQUEST: 'We could not process your request',
    ORG_DATE_FORMATE: 'orgDateFormate',
    ORG_CURRENCY_FORMAT: 'orgCurrencyFormat',
    ORG_CALENDER_YEAR: 'orgCalenderYear',
    roleName: 'userRoleName',
    institutionId: 'institutionId',
    GET_MENUS: '/get_access_menus',
    LOGGED_IN_SUCCESS: 'Logged in successfully',
    SERVER_DOWN_ERROR: 'Internal server error',
    UOM_CALUCULATION_DESTINATION_NAME_NULL_CHECK: 'Land UOM Name Is Not Updated Please Update It First ',
    TRUE: true,
    FALSE: false,
    ACTIVE: 1,
    IN_ACTIVE: 0,
    SUBMISSION_FOR_APPROVAL: 'Submission for Approval',
    CREATED: "Created",
    IN_PROGRESS: "In Progress",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    REQUEST_FOR_RESUBIMSSION: "Request for Resubmission",
    SINGLE_ACCOUNT_TYPE: "Single",
    IS_ACTIVE: 'Active',
    IN_ACTIVE_STATUS: 'In Active',
    IE_ROLE: "IE",
    IS_ROLE: "IS",
    CEO_ROLE: "CEO",
    MANAGER: "Manager",
    YES: 'Yes',
    NO: 'No',
    CUT_OFF_YEAR: 'Cut Of Year',
    EMAIL_PATTERN: '[A-Za-z0-9._%-]+@[A-Za-z0-9._%-]+\\.[a-z]{2,4}',
    NEW_EMAIL_PATTERN: '[a-z0-9._%-]+@[a-z0-9._%-]+\\.[a-z]{2,4}',
    MOBILE_PATTERN: '^[6-9]{1}[0-9]{9}',
    NAME_PATTERN: '^[^\\s][a-zA-Z-_ ()\\s]*$',
    NUMBER_OTP_PATTERN: '^[0-9]{1}[0-9]{5}',
    ALLOW_NUMBERS_ONLY: '^[1-9][0-9]*$',
    // ALLOW_NUMBERS_DECIMALS: '\d{1,2}(\.\d{1,2})|\d{0,9}',
    ALLOW_NUMBERS_DECIMALS: /^\d{0,2}(\.\d{1,2})?$/,
    ALLOW_TWO_DECIMALS: /^\d{0,13}(\.\d{1,2})?$/,
    ALLOW_TWO_NUMBERS_TWO_DECIMALS: /^\d{0,2}(\.\d{1,2})?$/,
    AMOUNT_DECIMAL: '/^[1-9]{1,18}(\.[1-9][1-9])?$/i',
    AMOUNT_PATTERN: '/^[0-9]+(\.[0-9]{1,2})?$/',
    NEW_AMOUNT_PATTERN: '^[1-9][0-9]*$',
    LAST_DOT: /\.(?=[^\.]+$)/,
    GST_NUMBER_PATTERN: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$',
    PAN_NUMBER_PATTERN: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$',
    IFSCNUMBER: '^[A-Za-z]{4}0[A-Z0-9a-z]{6}$',
    TAN_NUMBER: '^[A-Za-z]{4}[0-9]{5}[A-Za-z]$',
    AADHAR_PATTERN: '^([0-9]{12})$',
    ALLOW_NUMBERS: '^[1-9]{1}[0-9]*',
    ALLOW_DECIMALS_UPTO_TWO_PLACES: '^[0-9]*\.[0-9]$|^[0-9]*\.[0-9][0-9]$|^[1-9]{1}[0-9]*',

    // ACCOUNT_NUMBER_PATTERN: '^(\d{10}|\d{12})$',

    ACCOUNT_NUMBER_PATTERN: '^\\d{10}(\\d{2})?$',
    NEW_NAME_PATTERN: '^[a-zA-Z-\\s]*$',
    // NEW_NAME_PATTERN: '^[a-zA-Z-_.,/?()\\s]*$',
    // NEW_AMOUNT_PATTERN:'^[1-9][0-9]*$',
    // NEW_NAME_VALIDATIONS: '(?!\\s)[a-zA-Z0-9 ]*$',

    AMOUNT_DECIMAL_PATTERN: '^[1-9][0-9]*$',
    PERCENTAGE_PATTERN: '^(?!0(\.0+)?$)([1-9][0-9]*|0)\.[1-9][0-9]*$|^[1-9][0-9]*$',
    NEW_NAME_VALIDATIONS: '^(?!\\s)(?=.*[a-zA-Z0-9])[a-zA-Z0-9@#/\\-]*(?: [a-zA-Z0-9@#/\\-]+)*$',
    ONLY_CHARACTERS_NAME_VALIDATION: '^(?!\\s)(?=.*[a-zA-Z])[a-zA-Z@#/\\-]*(?: [a-zA-Z@#/\\-]+)*$',
    // NEW_NAME_VALIDATIONS:'^(?!\\s)[a-zA-Z0-9@#/\\-]*(?: [a-zA-Z0-9@#/\\-]+)*$',
    RELATIONSHIP_TYPE_NO_DATA_MESSAGE: "RelationshipType data not configured in Configuration, please update",
    SUB_PRODUCTS_NO_DATA_MESSAGE: "Products data not configured in Configuration, please update",
    ASSET_TYPE_NO_DATA_MESSAGE: "Asset Types data not configured in Configuration, please update",
    DOCUMENT_TYPE_NO_DATA_MESSAGE: "Document Types data not configured in Configuration, please update",
    WATER_SOURCE_TYPE_NO_DATA_MESSAGE: "Water Source Types data not configured in Configuration, please update",
    SOIL_TYPE_NO_DATA_MESSAGE: "Soil Types data not configured in Configuration, please update",
    // ALLOW_NUMBERS_DECIMALS: '\d{1,2}(\.\d{1,2})|\d{0,9}',
    AMOUNT_PATTERN_VALIDATION: '^(0|[1-9][0-9]*)$',
    // NEW_NAME_PATTERN: '^[a-zA-Z-_.,/?()\\s]*$',
    // NEW_AMOUNT_PATTERN:'^[1-9][0-9]*$',
    // NEW_NAME_VALIDATIONS: '^[a-zA-Z-./@#\\s]*$',
    OPERATION_TYPE_PATTERN: '^[a-zA-Z-\\s]*$',
    CASTE_NAME_VALIDATIONS: '^[a-zA-Z-/()\\s]*$',
    ALPHA_NAME_PATTERN: '[A-Za-z\\s]*',
    COMMUNITY_NAME_PATTERN: '^[a-zA-Z-_./()\\s]*$',
    DIPOSIT_NAME_PATTERN: '^[a-zA-Z-_./()\\s]*$',
    CROPS_NAME_PATTERN: '^[a-zA-Z-_./()\\s]*$',
    ALPHANUMERIC: '^[^\\s][a-z0-9A-Z-_.,/()\\s]*$',
    NEW_ALPHANUMERIC: '^[^\\s][a-z0-9A-Z-_/()%\\s]*$',
    ALLOW_NEW_NUMBERS: '^[^\\s][0-9\\s]*$',
    PINCODE_PATTERN: '^[1-9][0-9]{5}$',
    RATE_OF_INTERST: /^\d{0,2}(.\d{1,2})?$/,
    B_CLASS_MEMBER_CREATION: "b_class_member_creation",
    INDIVIDUAL_MEMBER_DTAILS: "Individual Member Details",
    GROUP_DETAILS: "Group Details",
    INSTITUTION_DETAILS: "Institution Details",
    MIN_DEPOSIT_AMOUNT_ERROR: "Minimum Deposit Amount Is Greater Than Or Equal To Maximum Deposit Amount",
    MIN_TENURE_AMOUNT_ERROR: "Minimum tenure should not be greater than Maximum tenure",
    MIN_PERIOD_IN_MONTHS_ERROR: "Minimum Period In Months Is Less Than Or Equal To Maximum Period In Months",
    COMMON_STATUS_ALREADY_EXISTED: "Common Status Already Existed",
    B_CLASS: "B-Class",
    INDIVIDUAL_MEMBER_TYPE_ID: 1,
    GROUP_MEMBER_TYPE_ID: 2,
    INSTITUTION_MEMBER_TYPE_ID: 3,
    KYC_APPROVED_NAME: "KYC Approved",
    KYC_NOT_APPROVED_NAME: "KYC Not Approved",
    SAVINGS_ACCOUNT: "Savings Account",

    MIN_AMOUNT_ERROR: " Maximum Amount Is Greater Than Or Equal To Minimum Amount",
    MIN_BORROWING_PERIOD_ERROR: "Maximum Borrowing Period Is Greater Than Or Equal To Minimum Borrowing Period",

    MIN_LOAN_PERIOD_ERROR: "Maximum Loan Period Is Greater Than Or Equal To Minimum Loan Period",
    MIN_SLAB_AMOUNT_ERROR: " Maximum Slab Amount Is Greater Than Or Equal To Minimum Slab Amount",
    MIN_CHARGES_ERROR: "Maximum Charges Is Greater Than Or Equal To Minimum Charges",
    GESTATION_PERIOD_ERROR: "Maximum Gestation Period Is Greater Than Or Equal To Minimum Gestation Period",
    //aploader constants names
    INDIVIDUAL_MEMBER_PHOTO_COPY_PATH: "Individual_Member_Photo_Copy_Path",
    INDIVIDUAL_MEMBER_SIGNED_COPY_PATH: "Individual_Member_Sighned_Copy_Path",

    GROUP_PHOTO_COPY_PATH: "Individual Member Photo Copy Path",
    GROUP_SIGNED_COPY_PATH: "Individual Member Sighned Copy Path",

    INSTITUTION_PHOTO_COPY_PATH: "Individual Member Photo Copy Path",
    INSTITUTION_SIGNED_COPY_PATH: "Individual Member Sighned Copy Path",


    SERVICE_TYPE_ALREADY_EXIST: "Service type already exists",
    DOCUMENT_TYPE_ALREADY_EXIST: "Document Type Already Exists",
    INTALLMENT_AMOUNT_SHOULD_BE_LESS_THAN_EQUAL: "Installment Amount Should be Less than or Equal to ",
    INTALLMENT_AMOUNT_SHOULD_BE_GREATHER_THAN_EQUAL: "Installment Amount Should be Greater than or Equal to ",
    INVALID_TENURE: "Invalid Ternure",
    CHARGES_TYPE_ALREADY_EXIST: "Charges Type Already Exists",
    CHARGES_TYPE_NO_DATA_MESSAGE: "ChargesType data not configured in Configuration, please update",
    PURPOSE_TYPE_ALREADY_EXIST: "Purpose Type Already Exists",
    COLLECTION_TYPE_ALREADY_EXIST: "Collection Type Already Exists",
    TENURE_TYPE_ALREADY_EXIST: "Tenure Type Already Exists",

    //preview messages

    VIEW_MEMBERSHIP: "Membership Application Created/Updated Sucessfully",
    SB_PRODUCT_DEFINITION: "Demand Deposits Product Definition Created/Updated Sucessfully",
    VIEW_SB_APPLICATION: "Demand Deposits Application Created/Updated Sucessfully",
    FD_NON_CUMULATIVE_PRODUCT_DEFINITION: "Fd Non Cumulative Product Definition Created/Updated Sucessfully",
    RD_PRODUCT_DEFINITION: "Recurring Deposit Product Definition Created/Updated Sucessfully",
    FD_CUMULATIVE_PRODUCT_DEFINITION: "Fd Cumulative Product Definition Created/Updated Sucessfully",
    FD_CUMMULATIVE_PREVIEW: "Fd Cumulative Application Created/Updated Sucessfully",
    FD_NON_CUMMULATIVE_PREVIEW: "Fd Non Cumulative Application Created/Updated Sucessfully",
    CI_LOAN__PRODUCT_DEFINITION: "CI Loan Product Definition Created/Updated Sucessfully",
    SI_LOAN_PRODUCT_DEFINITION: "SI Loan Product Definition Created/Updated Sucessfully",
    TERM_LOAN_PRODUCT_DEFINITION: "Term Loan Product Definition Created/Updated Sucessfully",
    SAO_LOAN_PRODUCT_DEFINITION: "SAO Loan Product Definition Created/Updated Sucessfully",
    DAILY_DEPOSIT_PRODUCT_DEFINITION: "Daily Deposit Product Definition Created/Updated Sucessfully",
    CI_BORROWING__PRODUCT_DEFINITION: "CI Borrowing Product Definition Created/Updated Sucessfully",
    SI_BORROWING_PRODUCT_DEFINITION: "SI Borrowing Product Definition Created/Updated Sucessfully",
    TERM_BORROWING_PRODUCT_DEFINITION: "Term Borrowing Product Definition Created/Updated Sucessfully",
    SAO_BORROWING_PRODUCT_DEFINITION: "SAO Borrowing Product Definition Created/Updated Sucessfully",
    INVESTMENTS_PRODUCT_DEFINITION: "Investments Product Definition Created/Updated Sucessfully",
    SI_LOAN_APPLICATION: "SI Loan  Application Created/Updated Sucessfully",
    SAO_LOAN_APPLICATION: "SAO Loan  Application Created/Updated Sucessfully",
    CI_BORROWING_APPLICATION: "CI Borrowing Application Created/Updated Sucessfully",
    SI_BORROWING_APPLICATION: "SI Borrowing Application Created/Updated Sucessfully",
    SAO_BORROWING_APPLICATION: "SAO Borrowing Application Created/Updated Sucessfully",
    TERM_BORROWING_APPLICATION: "Term Borrowing Application Created/Updated Sucessfully",
    AGENT_DETAILS_APPLICATION: "Agent Details Application Created/Updated Sucessfully",
    DEPOSIT_INVESTMENTS: "Deposit Investments Created/Updated Sucessfully",
    SHARE_INVESTMENTS: "Share Investments Created/Updated Sucessfully",
    RECURRING_DEPOSIT_PREVIEW: "Reccuring Deposit Application Created/Updated Sucessfully",
    UPDATE_USER_LOGOUT: '/update_user_logout',
    TERM_LOAN_APPLICATION: "Term Loan Product Definition Created/Updated Sucessfully",
    DATE_ERROR: "Effective Start Date Should Be Less Than Effective End Date",
    START_DATE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_END_DATA: "Start Date should be less than or equal to End Date",
    END_DATE_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_START_DATE: "End Date should be greater than or equal to Start Date",
    MINIMUM_DEPOSIT_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_DEPOSIT_AMOUNT: "Minimum Deposit Amount should be less than or equal to Maximum Deposit Amount",
    MAXIMUM_DEPOSIT_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_DEPOSIT_AMOUNT: "Maximum Deposit Amount should be greater than or equal to Minimum Deposit Amount",
    MINIMUM_TENURE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_TENURE: "Minimum Tenure should be less than or equal to Maximum Tenure",
    MAXIMUM_TENURE_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_TENURE: "Maximum Tenure should be greater than or equal to Minimum Tenure",
    EFFECTIVE_END_DATE_SHOULD_BE_GREATER_THAN_EFFECTIVE_START_DATE: "Effective End Date should be greater than or equal to Effective Start Date",
    EFFECTIVE_START_DATE_SHOULD_BE_LESS_THAN_EFFECTIVE_END_DATE: "Effective Start Date should be less than or equal to Effective End Date",
    REGISTRATION_DATE_SHOULD_LESSTHAN_ADMISSION_DATE: 'Registration Date Should be Less than Admission Date',
    KYC_DOC_TYPES_NO_DATA_MESSAGE: "KYC Documents Types data not configured in Configuration, please update",
    APPLICATION_DATE_SHOULD_NOT_LESS_THAN_ADMISSION_DATE: 'Application Date should not be less than Admission Date',
    SANCTION_DATE_SHOULD_NOT_LESS_THAN_ADMISSION_DATE: 'Sanction Date should not be less than Admission Date',
    SANCTION_DATE_SHOULD_NOT_LESS_THAN_APPLICATION_DATE: 'Sanction Date should not be less than Application Date',
    DUE_DATE_SHOULD_NOT_LESS_THAN_ADMISSION_DATE: 'Due Date should not be less than Admission Date',
    DUE_DATE_SHOULD_NOT_LESS_THAN_APPLICATION_DATE: 'Due Date should not be less than Application Date',
    DUE_DATE_SHOULD_NOT_LESS_THAN_SANCTION_DATE: 'Due Date should not be less than Sanction Date',
    SANCTION_DATE_SHOULD_NOT_GREATER_THAN_DUE_DATE: 'Sanction Date should not be greater than Due Date',
    SANCTION_DATE_SHOULD_NOT_GREATER_THAN_PRODUCT_END_DATE: 'Sanction Date should not be greater than Product End Date',
    APPLICATION_DATE_SHOULD_NOT_GREATER_THAN_SANCTION_DATE: 'Application Date should not greater than Sanction Date',
    APPLICATION_DATE_SHOULD_NOT_GREATER_THAN_DUE_DATE: 'Application Date should not greater than Due Date',
    MINIMUM_SLAB_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_SLAB_AMOUNT: "Minimum Slab Amount should be less than or equal to Maximum Slab Amount",
    MAXIMUM_SLAB_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_SLAB_AMOUNT: "Maximum Slab Amount should be greater than or equal to Minimum Slab Amount",
    APPORTION_ORDER_ALREADY_EXIST: 'Apportion Order Already Exist',
    MINIMUM_CHARGES_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_CHARGES: "Minimum Charges should be less than or equal to Maximum Charges",
    MAXIMUM_CHARGES_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_CHARGES: "Maximum Charges should be greater than or equal to Minimum Charges",
    MINIMUM_GESTATION_PERIOD_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_GESTATION_PERIOD: "Minimum Gestation Period should be less than or equal to Maximum Gestation",
    MAXIMUM_GESTATION_PERIOD_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_GESTATION_PERIOD: "Maximum Gestation should be greater than or equal to Minimum Gestation",
    CASTE_SUBCASTE_NO_DATA_MESSAGE: "Caste And SubCaste data not configured in Configuration, please update",
    SUB_CASTE_NO_DATA_MESSAGE: "Sub caste data not configured in Configuration, please update",
    COVERD_VILLAGES_NO_DATA_MESSAGE: "Covered Villages data not configured in Configuration, please update",
    IRRIGATION_NO_DATA_MESSAGE: "Irrigation data not configured in Configuration, please update",
    LAND_OWNERSHIP_NO_DATA_MESSAGE: "Land Ownership data not configured in Configuration, please update",
    LAND_TYPE_NO_DATA_MESSAGE: "LandType data not configured in Configuration, please update",
    LAND_VALUE_IS_LESSER_THAN_CULTIVABLE_LAND: 'Land Value Is Lesser Than Cultivable Land',
    LAND_SHOULD_NOT_EXCEED: "Land should not exceed more than 20 acres",
    Overall_LAND_SHOULD_NOT_EXCEED: "Overall land should not exceed more than 20 acres",
    CULTIVABLE_LAND_VALUE_IS_GREATER_THAN_LAND_VALUE: 'Cultivable Land Value Is Greater Than Land Value',
    CULTIVABLE_LAND_VALUE_IS_LESSER_THAN_UNDER_CULTIVATION_LAND: 'Cultivable Land Value Is Lesser Than Under Cultivation Land',
    UNDER_CULTIVATION_LAND_VALUE_IS_GREATER_THAN_LAND_VALUE: 'Under Cultivation Land Value Is Greater Than Cultivable Land Value',
    KHATA_ALREADY_EXITS_IN_SURVEY: 'Khata Number already exists in survey details.',
    SURVEY_NUMBER_ALREADY_EXIST: 'Survey Number Already Exist',
    PASSBOOK_ALREADY_EXITS_IN_SURVEY: 'Passbook already exists in survey details.',
    PASSBOOK_CANNOT_BE_REMOVED_PASSBOOK_ALREADY_EXITS_IN_SURVEY: 'Passbook Cannot be removed passbook already exists in survey',
    REQUESTED_DATE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_APPLICATION_DATE: "Requested date must be greater than or equal to application date.",
    SANCTION_DATE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_REQUESTED_DATE: "Sanction date must be greater than or equal to requested date.",
    DUE_DATE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_SANCTION_DATE: "Due date must be greater than or equal to sanction date.",
    KHATA_NUMBER_CANNOT_BE_REMOVED_KHATA_NUMBER_ALREADY_EXITS_IN_SURVEY: 'Khata Book No. cannot be removed, Khata Number already exists in survey details.',
    MIN_PERIOD_IN_MONTHS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAX_PERIOD_IN_MONTHS: "Minimum Period In Months should be less Than Or Equal To Maximum Period In Months",
    MAX_PERIOD_IN_MONTHS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAX_PERIOD_IN_MONTHS: "Maximum period in Months should be greater than or equal to Minimum period in Months",
    MINIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_OUT_PAN_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MINIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_PAN: "Minimum Deposit Limit Per Day Without Pan Should be Less Than or Equal To Minimum Deposit Limit Per Day With Pan",
    MINIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_PAN_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_OUT_PAN: "Minimum Deposit Limit Per Day With Pan Should be Greater Than or Equal To Minimum Deposit Limit Per Day Without Pan",
    MAXIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_OUT_PAN_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_PAN: "Maximum Deposit Limit Per Day Without Pan Should be Less Than or Equal To Maximum Deposit Limit Per Day With Pan",
    MAXIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_OUT_PAN_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MAXIMUM_DEPOSIT_LIMIT_PER_DAY_WITH_PAN: "Maximum Deposit Limit Per Day Without Pan Should be Greater Than or Equal To Maximum Deposit Limit Per Day With Pan",
    MINIMUM_WITH_DRAW_LIMIT_PER_DAY_WITH_OUT_PAN_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MINIMUM_WITH_DRAW_LIMIT_PER_DAY_WITH_PAN: "Miniimum Withdraw Limit Per Day Without Pan Should be Less Than or Equal To Miniimum Withdraw Limit Per Day With Pan",
    MINIMUM_WITH_DRAW_LIMIT_PER_DAY_WITH_PAN_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_WITH_DRAW_LIMIT_PER_DAY_WITH_OUT_PAN: "Minimum Withdraw Limit Per Day With Pan Should be Greater Than or Equal To Miniimum Withdraw Limit Per Day Without Pan",
    MAXIMUM_WITH_DRAW_LIMIT_SAME_BRANCH_ATM_PER_DAY_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_WITH_DRAW_LIMIT_OTHER_BRANCH_ATM_PER_DAY: "Maximum Withdraw Limit Other branch  ATM Per Day Should be Less Than or Equal To Maximum Withdraw Limit Same Branch ATM Per Day ",
    MAXIMUM_WITH_DRAW_LIMIT_OTHER_BRANCH_ATM_PER_DAY_WITH_OUT_PAN_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MAXIMUM_WITH_DRAW_SAME_BRANCH_ATM_LIMIT_PER_DAY: "Maximum Withdraw Limit Same Branch ATM Per Day Should be Greater Than or Equal To Maximum Withdraw Limit  Other Branch  ATM Per Day ",
    PRODUCT_NAME_ALREADY_EXIST: "Product Name Already Exist ",
    DAILY_DEPOSITS: "Daily Deposits",
    CLOSURE: "Closure",
    FORECLOSURE: "Foreclosure",
    SB_ACCOUNT: "sbAccount",
    CASH: "cash",
    PRINCIPLE: "Principle",
    PRINCIPLE_AND_INTEREST: "Principle And Interest",
    MANUAL_RENEWAL_AMOUNT: "Manual Renewal Amount",
    SCHEDULED: 'Scheduled',
    DEPOSITE_DATE_SHOULD_BE_LESSTHAN_PRODUCT_EFF_END_DATE: "Deposite date should be less than or equal to effective end date ",
    DEPOSITE_DATE_SHOULD_BE_GRATERTHAN_PRODUCT_EFF_START_DATE: "Deposite date should be grater than or equal to effective start date",
    DEPOSIT_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_DEPOSIT_AMOUNT: " Deposit Amount should be less than or equal to Maximum Deposit Amount",
    DEPOSIT_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_DEPOSIT_AMOUNT: " Deposit Amount should be greater than or equal to Minimum Deposit Amount",

    SANCTION_AMOUNT_SHOULD_BE_MIN_AND_MAX_AMOUNT: 'Sanction amount should be in between eligible min and max amount',
    LOAN_PERIOD_IN_MOTHS_SHOULD_BE_MIN_AND_MAX_AMOUNT: 'Loan period in months should be in between minLoanPeriod and maxLoanPeriod',
    COLLECTION: 'Collection',
    DISBURSEMENT: 'Disbursement',
    MINIMUM_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_AMOUNT: "Minimum Amount should be less than or equal to Maximum Amount",
    MAXIMUM_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_AMOUNT: "Maximum Amount should be greater than or equal to Minimum Amount",
    SANCTION_DATE_SHOULD_BE_IN_BETWEEN_MIN_AND_MAX_DATES: 'Sanction date should be in between product min and max dates',
    RELATION_TYPE_ALREADY_EXIST: 'Relation Type Already Exit',
    DATE_OF_BIRTH_SHOULD_NOT_BE_GREATER_THAN_ADMISSION_DATE: 'Date Of Birth Should Not Be Greater Than Admission Date',
    AGE_SHOULD_NOT_BE_ZERO: 'Age Shound Not Be Zero',
    POC_ALREADY_EXIST: 'POC Already Exist',
    VISIT_TENURE_CANNOT_EXCEED_30_DAYS: 'Visit tenure cannot exceed 30 days',
    VISIT_NUMBER_ALREADY_EXIST: 'Visit Number Already Exist',
    CROP: 'Crop',
    A_CLASS_MEMBER_MUST_BE_18_YEARS_OR_OLDER: 'A-Class members must be 18 or older',
    AGE_SHOULD_NOT_BE_ZERO_OR_NEGATIVE: 'Age should not be zero or negative',
    EMPLOYEE_JOININING_DATE_SHOULD_NOT_BE_LESS_THAN_DOB: 'Employee Joining Date should not be less than date of birth',
    THE_FILE_SIZE_SHOULD_BE_LESS_THEN_2MB: 'The file size should be less than 2MB.',
    THE_FILE_SIZE_SHOULD_BE_LESS_THEN_5MB: 'The file size should be less than 5MB.',
    UNSUPPORTED_FILE_TYPE: 'Unsupported file type',
    MINOR_ACCOUNT_MEMBERS_SHOULD_TAKE_ONLY_MAJOR_MEMBER_AS_NOMINEE: 'Minor Account Members Should Take Only Major Members As Nominee',

    PASSBOOK_ALREADY_EXITS: 'Passbook already exists.',
    GUARDIAN_MUST_BE_18_YEARS_OR_OLDER: 'Guardian must be 18 or above',
    AMOUNT_MISMTACH: 'Transaction amount is not equal to total denomination amount',
    DATE_OF_BIRTH_SHOUL_NOT_BE_GREATER_THAN_ADMISSION_DATE: 'Date Of Birth Should Not Be Greater Than Admission Date',
    TERM_LOAN_APPLICATION_DOWNLOAD_SECESSFULLY: "Term Loan Application Downloaded Successfully",
    UNABLE_TO_DOWNLOAD_TERM_LOAN_APPLICATION: "Unable to Download Application",

    // standing instructions
    STANDING_INSTRUCTION_RD_ACCOUNT_NOT_FOUND: "Account Not Found In Recurring Deposit account",
    STANDING_INSTRUCTION_TERM_LOAN_NOT_FOUND: "Account Not Found In Term Loan account",

    RECURRING_DEPOSITS_ACCOUNT_LIST_EMPTY: "No Accounts in Recurring Deposit ",
    TERM_LOAN_ACCOUNT_ARE_EMPTY: "No account In Term Loan",

    NO_OF_SHARES_LESS_THAN_TOTAL_SHARES: "No.Of Shares should be less than or equal to Total Shares",
    KYC_DETAILS_ALREADY_EXIST: "KYC Details Already Exist",
    PROMOTERS_MINIMUM_TWO_ARE_REQUIRED: "Promoters minimum three are required",
    MINORS_MEMBER_ACCOUNT_SHOULD_TAKE_MAJOR_NOMINEE_ONLY: "Minors Member Account Should Take Major Nominee Only",
    ADMISSION_DATE_SHOULD_NOT_BE_GRATER_THEN_EQUAL_TO_DATE_OF_BIRTH: "Admission Date Should Not be Grater Then or Equal to Date Of Birth",

    DUE_DATE_SHOULD_BE_GREATER_THAN_SANCTION_DUE_DATE: "Due Date Should Be Greater Than Saction Due Date",

    MINOR_AGE_LIMIT: 18,
    DEPOSIT_DATE_SHOULD_LESSTHAN_INSTALLMENT_DATE: "Deposit Date should be less than Installment Date",
    DOCUMENT_NOT_FOUND: "Document not Found",

    MIN_AGE_SHOULD_NOT_BE_GREATER_THAN_MAX_AGE: "Minmum Age Should Not Be Greater Than Maximum Age",
    MAX_AGE_SHOULD_NOT_BE_LESS_THAN_MIN_AGE: "Maximum Age Should Not Be less Than Minimum Age",
    MIN_SHARE_SHOULD_NOT_BE_GREATER_THAN_MAX_SHARE: "Minmum Share Should Not Be Greater Than Maximum Share",
    MAX_SHARE_SHOULD_NOT_BE_LESS_THAN_MIN_SHARE: "Maxmum Share Should Not Be Less Than Minimum Share",
    COMPLTED: "Completed",
    NOT_COMPLTED: "Not Complted",
    MINIMUM_SLAB_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUN_DEPOSIT_AMOUNT: "Minimum Slab Amount should be greater than or equal to Minimum Deposit Amount",
    MAXIMUM_SLAB_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_DEPOSIT_AMOUNT: "Maximum Slab Amount should be less than or equal to Maximum Deposit Amount",
    CHARGES_MUST_BE_BETWEEN_MIN_AND_MAX_CHARGES: "Charges Must be Between Min and Max Charges",
    NEW_NOMINEE: 1,
    SAME_AS_MEMBERSHIP_NOMINEE: 2,
    NO_NOMINEE: 3,
    NEW_GUARDIAN: 1,
    SAME_AS_MEMBERSHIP_GUARDIAN: 2,
    NO_GUARDIAN: 3,
    MINIMUM_GRACE_PERIOD_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_GRACE_PERIOD: "Minimum Grace Period should be less than or equal to Maximum Grace Period",
    MAXIMUM_GRACE_PERIOD_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_GRACE_PERIOD: "Maximum Grace Period should be greater than or equal to Minimum Grace Period",
    GESTATION_PERIOD_SHOULD_BE_MIN_AND_MAX_GESTATION_PERIOD: 'Gestation period should be in between Min Gestation Period and Max Gestation Period ',
    GRACE_PERIOD_SHOULD_BE_MIN_AND_MAX_GRACE_PERIOD: 'Grace period should be in between Min Grace Period and Max Grace Period ',
    PROMOTERS_SHOULD_HAVE_ONE_MEMBER_AS_POC: "Promoters Should Have One Member as POC",
    TERM_LOAN_KYC_CREATED_SUCESSFULLY: "Term Loan KYC Created Sucessfully",
    TERM_LOAN_KYC_UPDATED_SUCESSFULLY: "Term Loan KYC Updated Sucessfully",
    AGE_COMPARE_WITH_ZERO: 0,
    TOTAL_DISBURSMENT_PERCENTAGE_CANT_EXCEED: 'Total disbursement percentage cannot exceed 100%',
    FARMER_TYPE_NO_DATA_MESSAGE: "FarmerType data not configured in Configuration, please update",
    DESIGNATION_NO_DATA_MESSAGE: "Designation data not configured in Configuration, please update",
    UNABLE_TO_DOWNLOAD_PDF: "Unable to download pdf",
    MIN_AGE_SHOULD_BE_LESS_THAN_MAX_AGE: "minimum age  should be less than maximum age",
    MAX_SHARES_SHOULD_BE_LESS_THAN_MIN_SHARES: "Manimum share should be less than Maximum share",
    CARDS_SELECTION_MESSAGE: "Number of cards selction is six ",
    MIN_AGE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAX_AGE: "Minimum age  should be less than  Maximum age",
    MINIMUM_SHARES_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_SHARES: "Minimum shares should be less than  Maximum shares",
    MINIMUMSIZEINHEXTORS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUMSIZEINHECTORS: "Minimumsizeinhectors should be less than Maximumsizeinhectors",
    SELECT_STATE_AND_DISTRICT: "Select state and District",
    LAND_UOM_CONFIG_NO_DATA_MESSAGE: "Land UOM COnfig data not configured in Configuration, please update",
    ZERO_SHPOULD_NOT_ALLOWED: "Zero should not allowed",
    DELETED_SUCCESSFULLY: "Deleted Successfully",
    MEMBER_SHARE: "Member Share",
    NON_MEMBER_SHARE: "Non Member Share",
    TO_SAME_CLASS_SHARE: "To Same Class Share",
    TO_OTHER_CLASS_SHARE: "To Other Class Share",
    VIEW_SHARE_CAPITAL_CONFIG: "share_capital_config",
    VIEW_SHARE_APPROVAL_CONFIG: "share_management_configuration_approval_details",
    IS_VIEW: "view",
    IS_EDIT: "edit",
    MINIMUM_INTEREST_POSTING_AMOUNT_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_MAXIMUM_INTEREST_POSTING_AMOUNT: "Minimum Interest Posting Amount should be less than or equal to Maximum Interest Posting Amount",
    MAXIMUM_INTEREST_POSTING_AMOUNT_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO_MINIMUM_INTEREST_POSTING_AMOUNT: "Maximum Interest Posting Amount should be greater than or equal to Minimum Interest Posting Amount",
    END_DATE_MUST_BE_BETWEEN: "End date must be between ",
    TOTAL_SHARE_VALUE_AVAILABLE_BALANCE_CHECK: "Available Balance is less than the Total Share Value",
    CHARGES_AVAILABLE_BALANCE_CHECK: "Available Balance is less than the Charges"
};


